---
title: "Práctica 2: Limpieza y validación de los datos"
author: "Daniel Mirón Martínez, Alfonso Palazón González"
date: "15 de mayo de 2019"
output: 
  html_document:
    toc: yes
    number_sections: yes
    toc_depth: 2
    toc_float: true 
lang: es
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Descripción del dataset

El dataset se ha descargado desde [Kaggle](https://www.kaggle.com/uciml/red-wine-quality-cortez-et-al-2009), contiene información sobre distintas variedades de un vino tinto portugués conocido como "Vinho Verde". El dataset tiene un total de 12 campos y 1599 filas. Este es el detalle de los campos:

* **fixed acidity**, acidez fija del vino, la cantidad de ácidos que no se evaporan.
* **volatile acidity**, acidez volátil del vino, o cantidad de ácido acético. Valores altos producen un sabor avinagrado.
* **citric acid**, ácido cítrico, en pequeñas cantidades añade frescor y sabor al vino.
* **residual sugar**, azúcar residual, es la cantidad de azúcar que permanece en el vino una vez terminada la fermentación. Como mínimo suele haber un gramo de azúcar por litro, a partir de 45g/l se considera que el vino es dulce.
* **chlorides**, cloruros, cantidad de sal en el vino.
* **free sulfur dioxide**, dióxido de azufre libre, previene el crecimiento de microbiios y la oxidación del vino.
* **total sulfur dioxide**, dióxido de azufre total, es muy difícil de detectar pero en concentraciones superiores a 50ppm el dióxido de azufre se siente al olfato y en el sabor del vino.
* **density**, densidad, es similar a la del agua, y varía según la cantidad de alcohol y azúcar.
* **pH**, describe cómo de ácido es el vino en una escala de 0 (muy ácido) a 14 (muy base). La mayoría de vinos tienen un pH de entre 3 y 4.
* **sulphates**, sulfatos, es un aditivo del vino que influye en los niveles de dióxido de azufre.
* **alcohol**, porcentaje de alcohol que tiene el vino.
* **quality**, calidad del vino, se trata de la variable de salida, y que varía en una escala de 0 a 10.

**¿Por qué es importante y qué pregunta/problema pretende responder?**

Se desea averiguar qué variables influyen más en la calidad del vino. Se podrá crear un modelo de regresión e ir probando distintos valores en las variables para ver cómo podemos conseguir un vino de alta calidad.

Este tipo de estudios pueden ser muy útiles en la industria vinícola, que mueve mucho dinero. También pueden servir a los sumillers o personal de hostelería para explicar a sus clientes qué cualidades tiene un determinado vino y hacer que su experiencia sea mejor.

#Integración y selección de los datos de interés a analizar. 

#Limpieza de los datos.
##¿Los datos contienen ceros o elementos vacíos? ¿Cómo gestionarías cada uno de estos casos?
##Identificación y tratamiento de valores extremos.

#Análisis de los datos.
##Selección de los grupos de datos que se quieren analizar/comparar (planificación de los análisis a aplicar).
##Comprobación de la normalidad y homogeneidad de la varianza.
##Aplicación de pruebas estadísticas para comparar los grupos de datos. 

**En función de los datos y el objetivo del estudio, aplicar pruebas de contraste de hipótesis, correlaciones, regresiones, etc. Aplicar al menos tres métodos de análisis diferentes.**

#Representación de los resultados a partir de tablas y gráficas.

#Resolución del problema.
**A partir de los resultados obtenidos, ¿cuáles son las conclusiones? ¿Los resultados permiten responder al problema?**

#Código
**Hay que adjuntar el código, preferiblemente en R, con el que se ha realizado la limpieza, análisis y representación de los datos. Si lo preferís, también podéis trabajar en Python.**
